### ISSUE TITLE
i got error some errors when installing PhpOrient

### ISSUE THREAD

**Issue by lagoone** [Ostico/PhpOrient#114]
Bug :
1.	require-dev.Ostico/phpdoc-md is invalid, it should not contain uppercase characters. Please use ostico/phpdoc-md instead.
2.	Root composer.json requires phpdocumentor/phpdocumentor dev-master -> satisfiable by phpdocumentor/phpdocumentor[dev-master]

Fixing :
1.	Make changes to "require-dev" -> "Ostico/phpdoc-md" to "ostico/phpdoc-md"
2.	The removal of "require-dev" -> "phpdocumentor/phpdocumentor" was replaced by a manual installation of https://github.com/phpDocumentor/phpDocumentor/releases

I already turn on sockets extension on php.ini but the next error is  :

>Fatal error: Uncaught PhpOrient\Exceptions\SocketException: Error 0 : The operation completed successfully in C:\xampp\htdocs\if5100\PhpOrient\src\PhpOrient\Protocols\Binary\OrientSocket.php:91 Stack trace: #0 C:\xampp\htdocs\if5100\PhpOrient\src\PhpOrient\Protocols\Binary\SocketTransport.php(146): PhpOrient\Protocols\Binary\OrientSocket->connect() #1 C:\xampp\htdocs\if5100\PhpOrient\src\PhpOrient\Protocols\Binary\Abstracts\Operation.php(76): PhpOrient\Protocols\Binary\SocketTransport->getSocket() #2 C:\xampp\htdocs\if5100\PhpOrient\src\PhpOrient\Protocols\Binary\SocketTransport.php(223): PhpOrient\Protocols\Binary\Abstracts\Operation->__construct(Object(PhpOrient\Protocols\Binary\SocketTransport)) #3 C:\xampp\htdocs\if5100\PhpOrient\src\PhpOrient\Protocols\Binary\SocketTransport.php(161): PhpOrient\Protocols\Binary\SocketTransport->operationFactory('PhpOrient\\Proto...', Array) #4 C:\xampp\htdocs\if5100\PhpOrient\src\PhpOrient\PhpOrient.php(247): PhpOrient\Protocols\Binary\SocketTransport->execute('connect', Array) #5 C:\xampp\htdocs\if5100\coba.php(8): PhpOrient\PhpOrient->connect() #6 {main} thrown in C:\xampp\htdocs\if5100\PhpOrient\src\PhpOrient\Protocols\Binary\OrientSocket.php on line 91

**Comment by lagoone** [comment]
it turns out that OrientDB does not support PHP version 8, when I change it to PHP version 7.x everything runs normally.
