### ISSUE TITLE
Protocol version 32 support

### ISSUE THREAD

**Issue by andreyvk** [Ostico/PhpOrient#45]
Hi @Ostico,

Do you have plans to support protocol version 32? I've downloaded OrientDB v2.1.2 and the whole thing stopped working, so I had to roll back to the previous version. 

Below is the error:

```
[ERROR]: ORIENTDB connection failed : Protocol version 32 is not supported.
PHP Fatal error:  Uncaught exception 'PhpOrient\Exceptions\PhpOrientWrongProtocolVersionException' with message 'Protocol version 32 is not supported.' in /home/ubuntu/shared/www/test/lib/vendor/ostico/phporient/src/PhpOrient/Protocols/Binary/OrientSocket.php:92
Stack trace:
#0 /home/ubuntu/shared/www/test/lib/vendor/ostico/phporient/src/PhpOrient/Protocols/Binary/SocketTransport.php(138): PhpOrient\Protocols\Binary\OrientSocket->connect()
#1 /home/ubuntu/shared/www/test/lib/vendor/ostico/phporient/src/PhpOrient/Protocols/Binary/Abstracts/Operation.php(73): PhpOrient\Protocols\Binary\SocketTransport->getSocket()
#2 /home/ubuntu/shared/www/test/lib/vendor/ostico/phporient/src/PhpOrient/Protocols/Binary/SocketTransport.php(174): PhpOrient\Protocols\Binary\Abstracts\Operation->__construct(Object(PhpOrient\Protocols\Binary\SocketTransport))
#3 /home/ubuntu/shared/www/test/lib/vendor/ostico/phporient/src/PhpOrient/Protocols/Binary/SocketTransport.php(153): PhpOrient\Protocols\Binary\SocketTransport->operationFactory('connect', in /home/ubuntu/shared/www/test/base/models/BaseModel.php on line 116
```

**Comment by Ostico** [comment]
Yes, i think this evening or tomorrow at max.

**Comment by andreyvk** [comment]
Thanks!

**Comment by oharlem** [comment]
+1
Really need this support. Just discovered a bug in 2.1.0 (issue handling quotes) that was fixed in 2.1.2, so need to migrate to 2.1.2.

**Comment by andreyvk** [comment]
+1

**Comment by bbgg91** [comment]
Was this problem fixed as I am getting the same exemption with version 2.1.9 of orientdb??
